config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_param, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      #do something
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  private
    def set_param
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from getting created</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to "Back to articles listing", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>
<p>
  <%= link_to "Create new article", new_article_path %>
</p>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article </h1>

<p>
  Title: <%= @article.title %>
</p>

<p>
  Description: <%= @article.description %>
</p>

<%= link_to "Edit this article", edit_article_path(@article) %> |
<%= link_to "Back to articles listing", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/messages' %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Eu sou a about!</h1>

<%= link_to 'home', root_path%>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to my webpage!</title>
    <meta charset="utf-8">

    <link rel="stylesheet" href="css/estilos.css">
    <style>
      body {
        width: 940px;
        margin-left: auto;
        margin-right: auto;
      }

      img {
        width: 940px;
      }

      header {
        text-align: center;
      }

      section {
        width: 400px;
      }

      .esq {
        float: left;
      }

      .dir {
        float: right;
      }
    </style>

  </head>

  <body>

    <!-- Cabecalho -->
    <header>
      <h1>Welcome to my webpage!</h1>
      <%= image_tag 'banner.jpg'%>
    </header>
    <!-- Fim cabecalho -->

    <!-- conteudo -->
    <div>

      <!-- conteudo da esquerda -->
      <section class="esq">
        <p>
          In 1901 English quadricycle and bicycle maker Royal Enfield introduced
          its first motorcycle, with a 239 cc engine mounted in the front and
          driving the rear wheel through a belt. In 1898, English bicycle maker
          Triumph decided to extend its focus to include motorcycles, and by 1902,
          the company had produced its first motorcycle—a bicycle fitted with a
          Belgian-built engine. A year later, it was the largest motorcycle manufacturer
          with an annual production of over 500 units. Other British firms were Norton
          and Birmingham Small Arms Company who began motorbike production in 1902 and
          1910, respectively.
        </p>
      </section>
      <!-- Fim conteudo da esquerda -->

      <!-- conteudo da direita -->
      <section class="dir">
        <p>
          In 1901 English quadricycle and bicycle maker Royal Enfield introduced
          its first motorcycle, with a 239 cc engine mounted in the front and
          driving the rear wheel through a belt. In 1898, English bicycle maker
          Triumph decided to extend its focus to include motorcycles, and by 1902,
          the company had produced its first motorcycle—a bicycle fitted with a
          Belgian-built engine. A year later, it was the largest motorcycle manufacturer
          with an annual production of over 500 units. Other British firms were Norton
          and Birmingham Small Arms Company who began motorbike production in 1902 and
          1910, respectively.
        </p>
      </section>
      <!-- Fim conteudo da direita -->

    </div>
    <!-- Fim conteudo -->

    <!-- Rodape -->
    <footer>
      <%= link_to 'Alpha Blog', articles_path %> | <%= link_to 'about', about_path %>
    </footer>
  </body>

</html>